# https://taskfile.dev

version: '3'

vars:
  VERSION: 0.1

tasks:
  build:
    cmds:
      - gem build packfest.gemspec

  install-deps:
    desc: Install dependencies
    cmds:
      - gem install --conservative dry-cli colorize

  install:
    cmds:
      - task: install-deps
      - task: build
      - gem install --local ./packfest-{{.VERSION}}.gem
